try destry

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,10 +12,10 @@ commands:
           when: on_fail
           command: |
             # aws cloudformation describe-stack-events --stack-name udapeople-backend-<< parameters.workflow_id >>
-            echo "Destroyed env: << parameters.workflow_id >> "
+            echo "Destroying env: << parameters.workflow_id >> "
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
-            exit 1
+            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
@@ -227,11 +227,11 @@ jobs:
             then
                 curl https://kvdb.io/5j2Vyk9xyHqE3ZZVQMGA7M/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
-     # Here's where you will add some code to rollback on failure      
+     # Here's where you will add some code to rollback on failure  
+
   deploy-frontend:
     docker:
       - image: cimg/python:3.8.13
-      # Docker image here that supports AWS CLI
     steps:
       - checkout
       - attach_workspace:
@@ -280,7 +280,11 @@ jobs:
             npm run build
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # Here's where you will add some code to rollback on failure      
+            exit 1
+      # Here's where you will add some code to rollback on failure   
+      - destroy-environment:
+          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+        
                     
 #   deploy-backend:
 #     docker:
